services:
  - type: web
    name: kite-trading-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py kite_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 